version: "3.8"
services:
  db:
    image: postgres
    container_name: ExpenseTrackerDB
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ExpenseTrackerDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db-storage:/var/lib/postgresql/data

     

  pgadmin:
    image: dpage/pgadmin4
    container_name: expense-pga
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@yahoo.com
      PGADMIN_DEFAULT_PASSWORD: password
